apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-helm
  namespace: argo-cd
spec:
  project: default
  sources:
    - repoURL: https://github.com/chroju/infrastructure
      targetRevision: main
      ref: gitRepo
    - repoURL: https://prometheus-community.github.io/helm-charts
      chart: prometheus
      targetRevision: 19.3.3
      helm:
        valueFiles:
          - $gitRepo/kubernetes/prometheus/values/values.yaml
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false
      allowEmpty: false
