apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-helm
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 19.3.3
    helm:
      parameters:
        - name: "alertmanager.enabled"
          value: "false"
        - name: "prometheus-pushgateway.enabled"
          value: "false"
        - name: "extraScrapeConfigs"
          value: |
            - job_name: "remo"
              scrape_interval: 60s
              dns_sd_configs:
                - names: ['remo-exporter.remo-exporter']
                  port: 9352
                  type: A
                  refresh_interval: 5s
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
