apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus
  namespace: argo-cd
spec:
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus
    targetRevision: 19.3.3
    helm:
      parameters:
        alertmanager:
          enabled: false
        prometheus-pushgateway:
          enabled: false
  destination:
    server: "https://kubernetes.default.svc"
    namespace: prometheus
