apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: remo-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: aws
    kind: SecretStore
  target:
    name: prometheus
    template:
      data:
        engineVersion: v2
        remoteWrite: |
          server:
            remoteWrite:
            - url: "https://prometheus-prod-18-prod-ap-southeast-0.grafana.net/api/prom/push"
              basic_auth:
                username: "{{.grafanaCloudUsername}}"
                password: "{{.grafanaCloudPassword}}"
  data:
    - secretKey: grafanaCloudUsername
      remoteRef:
        key: /chroju/prometheus/grafana-cloud-username
    - secretKey: grafanaCloudPassword
      remoteRef:
        key: /chroju/prometheus/grafana-cloud-password
