apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pleroma-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: aws
    kind: SecretStore
  data:
    - secretKey: pleroma-db-password
      remoteRef:
        key: /chroju/pleroma/db-password
