apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pleroma-pvc
spec:
  storageClassName: pleroma
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pleroma-data-pvc
spec:
  storageClassName: pleroma-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
