kind: PersistentVolume
apiVersion: v1
metadata:
  name: pleroma-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  storageClassName: pleroma
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/pvs/pleroma
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: pleroma-data-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  storageClassName: pleroma-data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/pvs/pleroma-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists
