apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider:
    aws:
      service: ParameterStore
      region: ap-northeast-1
