apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: {{ .Values.metadata.namespace }}
spec:
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: kubernetes/argo-cd
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
      - values.yaml
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: argo-cd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
