apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps
  namespace: argo-cd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - appname: namespace
            repo: https://github.com/chroju/infrastructure
            path: kubernetes/namespace
            namespace: kube-system # temp
          - appname: prometheus
            repo: https://github.com/chroju/infrastructure
            path: kubernetes/prometheus
            namespace: kube-system # temp
          - appname: remo-exporter
            repo: https://github.com/chroju/infrastructure
            path: kubernetes/remo-exporter
            namespace: remo-exporter
          # - appname: external-secrets
          #   repo: https://github.com/chroju/infrastructure
          #   path: kubernetes/external-secrets
          #   namespace: kube-system # temp
  template:
    metadata:
      name: "{{.appname}}"
    spec:
      project: default
      source:
        repoURL: "{{.repo}}"
        targetRevision: HEAD
        path: "{{.path}}"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{.namespace}}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: false
