alertmanager:
  enabled: false
prometheus-pushgateway:
  enabled: false
server:
  persistentVolume:
    enabled: true
    storageClass: prometheus
    size: 2Gi
  # extraSecretMounts:
  #   - name: password
  #     mountPath: /etc/secrets
  #     subPath: ""
  #     secretName: prometheus-secrets
  #     readOnly: true
  remoteWrite:
    - url: "https://prometheus-prod-18-prod-ap-southeast-0.grafana.net/api/prom/push"
extraScrapeConfigs: |
  - job_name: "remo"
    scrape_interval: 60s
    dns_sd_configs:
      - names: ['remo-exporter.remo-exporter']
        port: 9352
        type: A
        refresh_interval: 5s
  - job_name: "argocd"
    scrape_interval: 60s
    dns_sd_configs:
      - names: ['argo-cd-argocd-application-controller-metrics.argo-cd']
        port: 8082
        type: A
        refresh_interval: 5s
