apiVersion: apps/v1
kind: Deployment
metadata:
  name: remo-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: remo-exporter
  template:
    metadata:
      labels:
        app: remo-exporter
    spec:
      containers:
        - name: remo-exporter
          image: kenfdev/remo-exporter:latest
          ports:
            - containerPort: 9352
              protocol: TCP
          env:
            - name: OAUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: remo-secrets
                  key: remo-oauth-token
