apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: remo-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: aws
    kind: SecretStore
  data:
    - secretKey: remo-oauth-token
      remoteRef:
        key: /chroju/remo/oauth-token
