apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: aws
    kind: SecretStore
  data:
    - secretKey: cloudflared-tunnel-token
      remoteRef:
        key: /chroju/cloudflared/tunnel-token
