apiVersion: v1
kind: ConfigMap
metadata:
  name: influxdb-conf
  namespace: grafana
data:
  influxdb.conf: |
    [meta]
      dir = "/var/lib/influxdb/meta"

    [data]
      dir = "/var/lib/influxdb/data"
      engine = "tsm1"
      wal-dir = "/var/lib/influxdb/wal"

    [admin]
      enabled = false

    [http]
      enabled = true
      auth-enabled = true
