apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        # - name: grafana
        #   image: grafana/grafana:9.3.6
        #   imagePullPolicy: IfNotPresent
        #   ports:
        #     - containerPort: 3000
        #       name: http-grafana
        #       protocol: TCP
        #   readinessProbe:
        #     failureThreshold: 3
        #     httpGet:
        #       path: /robots.txt
        #       port: 3000
        #       scheme: HTTP
        #     initialDelaySeconds: 10
        #     periodSeconds: 30
        #     successThreshold: 1
        #     timeoutSeconds: 2
        #   livenessProbe:
        #     failureThreshold: 3
        #     initialDelaySeconds: 30
        #     periodSeconds: 10
        #     successThreshold: 1
        #     tcpSocket:
        #       port: 3000
        #     timeoutSeconds: 1
        #   resources:
        #     requests:
        #       cpu: 250m
        #       memory: 250Mi
        #     limits:
        #       cpu: 250m
        #       memory: 250Mi
        #   volumeMounts:
        #     - mountPath: /var/lib/grafana
        #       name: grafana-pv
        - name: influxdb
          image: influxdb:2.7.10
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
              name: http-influxdb
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 250m
              memory: 250Mi
          volumeMounts:
            - mountPath: /var/lib/influxdb
              name: influxdb-pv
            - mountPath: /etc/influxdb
              readOnly: true
              name: influxdb-conf
      volumes:
        # - name: grafana-pv
        #   persistentVolumeClaim:
        #     claimName: grafana-pvc
        - name: influxdb-pv
          persistentVolumeClaim:
            claimName: influxdb-pvc
        - name: influxdb-conf
          configMap:
            name: influxdb-conf
            items:
              - key: influxdb.conf
                path: influxdb.conf
