apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana
  name: grafana
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: influxdb
          image: influxdb:2.7.12
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8086
              name: http-influxdb
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 250Mi
            limits:
              cpu: 250m
              memory: 250Mi
          volumeMounts:
            - mountPath: /var/lib/influxdb2
              name: influxdb-pv
            - mountPath: /etc/influxdb2
              name: influxdb-conf-pv
      volumes:
        - name: influxdb-pv
          persistentVolumeClaim:
            claimName: influxdb-pvc
        - name: influxdb-conf-pv
          persistentVolumeClaim:
            claimName: influxdb-conf-pvc
