kind: PersistentVolume
apiVersion: v1
metadata:
  name: grafana-pv
spec:
  storageClassName: grafana
  capacity:
    storage: 200Mi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/pvs/grafana
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists
