apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
spec:
  storageClassName: grafana
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 200Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-pvc
spec:
  storageClassName: influxdb
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Mi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influxdb-conf-pvc
spec:
  storageClassName: influxdb-conf
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Mi
