apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bitwarden
  name: bitwarden
  namespace: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: bitwarden
  template:
    metadata:
      labels:
        pod: bitwarden
    spec:
      containers:
        - image: ghcr.io/bitwarden/self-host:2025.8.2-beta
          name: bitwarden
          # livenessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 2000
          #   failureThreshold: 1
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          resources:
            requests:
              cpu: 200m
              memory: 250Mi
            limits:
              cpu: 200m
              memory: 250Mi
          ports:
            - containerPort: 8080
          env:
            - name: BW_DOMAIN
              value: bw.chroju.dev
            - name: BW_DB_PROVIDER
              value: sqlite
            - name: BW_INSTALLATION_ID
              valueFrom:
                secretKeyRef:
                  name: bitwarden-secrets
                  key: bw-installation-id
            - name: BW_INSTALLATION_KEY
              valueFrom:
                secretKeyRef:
                  name: bitwarden-secrets
                  key: bw-installation-key
            - name: globalSettings__mail__smtp__host
              value: smtp.gmail.com
            - name: globalSettings__mail__smtp__port
              value: '587'
            - name: globalSettings__mail__smtp__ssl
              value: 'false'
            - name: globalSettings__mail__replyToEmail
              valueFrom:
                secretKeyRef:
                  name: bitwarden-secrets
                  key: bw-reply-to-email
            - name: globalSettings__mail__smtp__username
              valueFrom:
                secretKeyRef:
                  name: bitwarden-secrets
                  key: bw-smtp-username
            - name: globalSettings__mail__smtp__password
              valueFrom:
                secretKeyRef:
                  name: bitwarden-secrets
                  key: bw-smtp-password
          volumeMounts:
            - mountPath: /etc/bitwarden
              name: bitwarden-pv
      volumes:
        - name: bitwarden-pv
          persistentVolumeClaim:
            claimName: bitwarden-pvc
