apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bitwarden
  name: bitwarden
  namespace: bitwarden
spec:
  replicas: 1
  selector:
    matchLabels:
      pod: bitwarden
  template:
    metadata:
      labels:
        pod: bitwarden
    spec:
      containers:
        - image: bitwarden/self-host:beta
          name: bitwarden
          # livenessProbe:
          #   httpGet:
          #     path: /ready
          #     port: 2000
          #   failureThreshold: 1
          #   initialDelaySeconds: 10
          #   periodSeconds: 10
          resources:
            requests:
              cpu: 200m
              memory: 250Mi
            limits:
              cpu: 200m
              memory: 250Mi
          ports:
            - containerPort: 80
          env:
            - name: BW_DOMAIN
              value: bw.chroju.dev
            - name: BW_DB_PROVIDER
              value: sqlite
          volumeMounts:
            - mountPath: /etc/bitwarden
              name: bitwarden-pv
      volumes:
        - name: bitwarden-pv
          persistentVolumeClaim:
            claimName: bitwarden-pvc
