apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: bitwarden-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  secretStoreRef:
    name: aws
    kind: SecretStore
  data:
    - secretKey: bw-installation-id
      remoteRef:
        key: /chroju/bitwarden/installtion-id
    - secretKey: bw-installation-key
      remoteRef:
        key: /chroju/bitwarden/installtion-key
    - secretKey: bw-reply-to-email
      remoteRef:
        key: /chroju/bitwarden/reply-to-email
    - secretKey: bw-smtp-username
      remoteRef:
        key: /chroju/bitwarden/smtp-username
    - secretKey: bw-smtp-password
      remoteRef:
        key: /chroju/bitwarden/smtp-password
