kind: PersistentVolume
apiVersion: v1
metadata:
  name: bitwarden-pv
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  storageClassName: bitwarden
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  local:
    path: /data/pvs/bitwarden
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: Exists
