name: Terraform workflow
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - terraform/kops/**
  push:
    branches:
      - main
    paths:
      - terraform/kops/**

permissions:
  id-token: write
  contents: write    # This is required for actions/checkout@v1
env:
  terraform_version: 1.0.10
  tfnotify_version: 0.7.0

jobs:
  terraform-automation:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: ./terraform/kops/
    steps:
      - name: git clone the repository
        uses: actions/checkout@v1
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@master
        with:
          role-to-assume: ${{ secrets.AWS_IAM_ROLE_ARN }}
          role-session-name: github-actions
          aws-region: ap-northeast-1
      - name: setup tfnotify
        run: |
          sudo curl -fL -o tfnotify.tar.gz https://github.com/mercari/tfnotify/releases/download/v${{ env.tfnotify_version }}/tfnotify_linux_amd64.tar.gz
          sudo tar -C /usr/bin -xzf ./tfnotify.tar.gz
      - name: setup terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ env.terraform_version }}
      - name: setup terraformrc
        run: echo '${{ secrets.TERRAFORMRC }}' > $HOME/.terraformrc
      - name: terraform init
        id: init
        run: terraform init
      - name: terraform validate
        id: validate
        run: terraform validate -no-color
      - name: notify terraform plan result
        if: github.event_name == 'pull_request' 
        # https://sue445.hatenablog.com/entry/2021/01/07/004835
        run: |
          if [ -n "$PR_HEAD_SHA" ]; then
            export GITHUB_SHA=$PR_HEAD_SHA
          fi
          terraform plan -no-color | tfnotify --config ../tfnotify_github.yaml plan
        env:
          GITHUB_TOKEN: ${{ secrets.github_token }}
          PR_HEAD_SHA: ${{ github.event.pull_request.head.sha }}
      - name: terraform apply
        if: github.event_name == 'push'
        run: |
          terraform apply -auto-approve | tfnotify --config ../tfnotify_slack.yaml apply
        env:
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL }}
          SLACK_BOT_NAME: tfnotify
          GITHUB_TOKEN: ${{ secrets.github_token }}
