name: ci

on:
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: name/app
          tags: |
            type=schedule,pattern={{date 'YYYYMMDD-hhmmss' tz='Asia/Tokyo'}}
            type=raw,value={{date 'YYYYMMDD-hhmmss' tz='Asia/Tokyo'}}-dev
